/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PatriarchInfo {
    title: string;
    inspirationalMessage: string;
    name: string;
}
export interface GalleryPhoto {
    id: string;
    photoData: string;
    approvedStatus: string;
    uploaderName: string;
    createdAt: Time;
    caption: string;
    category: string;
    uploadedBy: string;
}
export type Time = bigint;
export interface RelationshipRequest {
    id: string;
    status: string;
    relationType: string;
    note: string;
    createdAt: Time;
    toMemberId: string;
    fromUserId: string;
    fromMemberName: string;
}
export interface FamilyMember {
    id: string;
    occupation: string;
    photoData: string;
    additionalInfo: string;
    roadName: string;
    fatherId: string;
    spouseIds: Array<string>;
    houseNumber: string;
    childrenNames: string;
    marriageDate: string;
    fatherFullName: string;
    deathDate: string;
    birthDate: string;
    birthTime: string;
    motherInLawName: string;
    isDeceased: boolean;
    brotherIds: Array<string>;
    motherInLawId: string;
    name: string;
    createdAt: Time;
    createdBy: string;
    motherFullName: string;
    education: string;
    whatsapp: string;
    nativeVillage: string;
    motherName: string;
    husbandName: string;
    district: string;
    fatherInLawName: string;
    fatherName: string;
    sisterNames: string;
    bloodGroup: string;
    address: string;
    village: string;
    gender: string;
    occupationType: string;
    landmark: string;
    sisterIds: Array<string>;
    cityVillage: string;
    mobile: string;
    fatherInLawId: string;
    pincode: string;
    spouseName: string;
    lastName: string;
    childrenIds: Array<string>;
    maritalStatus: string;
    brotherNames: string;
    motherId: string;
    firstName: string;
}
export interface PendingRegistration {
    id: string;
    occupation: string;
    status: string;
    photoData: string;
    additionalInfo: string;
    roadName: string;
    houseNumber: string;
    childrenNames: string;
    marriageDate: string;
    fatherFullName: string;
    deathDate: string;
    birthDate: string;
    birthTime: string;
    motherInLawName: string;
    isDeceased: boolean;
    name: string;
    motherFullName: string;
    education: string;
    whatsapp: string;
    nativeVillage: string;
    motherName: string;
    husbandName: string;
    email: string;
    district: string;
    fatherInLawName: string;
    fatherName: string;
    sisterNames: string;
    bloodGroup: string;
    address: string;
    gender: string;
    occupationType: string;
    landmark: string;
    cityVillage: string;
    mobile: string;
    pincode: string;
    spouseName: string;
    registeredAt: Time;
    lastName: string;
    maritalStatus: string;
    brotherNames: string;
    firstName: string;
}
export interface UserProfile {
    id: string;
    name: string;
    createdAt: Time;
    role: UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    passwordHash: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFamilyMember(member: FamilyMember): Promise<string>;
    addGalleryPhoto(photo: GalleryPhoto): Promise<string>;
    adminToggleUserActive(email: string, isActive: boolean): Promise<void>;
    adminUpdatePatriarchInfo(newInfo: PatriarchInfo): Promise<void>;
    adminUpdateUserRole(email: string, newRole: UserRole): Promise<void>;
    approveGalleryPhoto(photoId: string): Promise<void>;
    approveRegistration(email: string): Promise<void>;
    approveRelationshipRequest(requestId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteFamilyMember(id: string): Promise<void>;
    deleteGalleryPhoto(photoId: string): Promise<void>;
    getAllFamilyMembers(): Promise<Array<FamilyMember>>;
    getAllFamilyMembersForBackup(): Promise<Array<FamilyMember>>;
    getAllGalleryPhotosForBackup(): Promise<Array<GalleryPhoto>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAllUsersForBackup(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getFamilyMember(id: string): Promise<FamilyMember>;
    getGalleryPhotoCount(): Promise<bigint>;
    getGalleryPhotos(): Promise<Array<GalleryPhoto>>;
    getGalleryPhotosByCategory(category: string): Promise<Array<GalleryPhoto>>;
    getMyRelationshipRequests(userId: string): Promise<Array<RelationshipRequest>>;
    getPatriarchId(): Promise<string>;
    getPatriarchInfo(): Promise<PatriarchInfo>;
    getPendingGalleryPhotos(): Promise<Array<GalleryPhoto>>;
    getPendingRegistrations(): Promise<Array<PendingRegistration>>;
    getRelationshipRequests(): Promise<Array<RelationshipRequest>>;
    getUserProfile(userPrincipal: Principal): Promise<UserProfile>;
    getUserProfileByEmail(email: string): Promise<UserProfile>;
    isCallerAdmin(): Promise<boolean>;
    isUserActive(email: string): Promise<boolean>;
    loginWithPassword(email: string, providedPassword: string): Promise<UserProfile>;
    registerUser(profile: UserProfile): Promise<void>;
    rejectRegistration(email: string): Promise<void>;
    rejectRelationshipRequest(requestId: string, note: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPendingRegistration(reg: PendingRegistration): Promise<void>;
    submitRelationshipRequest(request: RelationshipRequest): Promise<string>;
    updateFamilyMember(member: FamilyMember): Promise<void>;
    updateGalleryPhotoCategory(photoId: string, newCategory: string): Promise<void>;
    updateUserProfile(updatedProfile: UserProfile): Promise<void>;
}
import type { Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFamilyMember(arg0: FamilyMember): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addFamilyMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFamilyMember(arg0);
            return result;
        }
    }
    async addGalleryPhoto(arg0: GalleryPhoto): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryPhoto(arg0);
            return result;
        }
    }
    async adminToggleUserActive(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminToggleUserActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminToggleUserActive(arg0, arg1);
            return result;
        }
    }
    async adminUpdatePatriarchInfo(arg0: PatriarchInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdatePatriarchInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdatePatriarchInfo(arg0);
            return result;
        }
    }
    async adminUpdateUserRole(arg0: string, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async approveGalleryPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveGalleryPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveGalleryPhoto(arg0);
            return result;
        }
    }
    async approveRegistration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRegistration(arg0);
            return result;
        }
    }
    async approveRelationshipRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRelationshipRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRelationshipRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteFamilyMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFamilyMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFamilyMember(arg0);
            return result;
        }
    }
    async deleteGalleryPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryPhoto(arg0);
            return result;
        }
    }
    async getAllFamilyMembers(): Promise<Array<FamilyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFamilyMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFamilyMembers();
            return result;
        }
    }
    async getAllFamilyMembersForBackup(): Promise<Array<FamilyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFamilyMembersForBackup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFamilyMembersForBackup();
            return result;
        }
    }
    async getAllGalleryPhotosForBackup(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryPhotosForBackup();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryPhotosForBackup();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersForBackup(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersForBackup();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersForBackup();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyMember(arg0: string): Promise<FamilyMember> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyMember(arg0);
            return result;
        }
    }
    async getGalleryPhotoCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryPhotoCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryPhotoCount();
            return result;
        }
    }
    async getGalleryPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryPhotos();
            return result;
        }
    }
    async getGalleryPhotosByCategory(arg0: string): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryPhotosByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryPhotosByCategory(arg0);
            return result;
        }
    }
    async getMyRelationshipRequests(arg0: string): Promise<Array<RelationshipRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRelationshipRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRelationshipRequests(arg0);
            return result;
        }
    }
    async getPatriarchId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatriarchId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatriarchId();
            return result;
        }
    }
    async getPatriarchInfo(): Promise<PatriarchInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatriarchInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatriarchInfo();
            return result;
        }
    }
    async getPendingGalleryPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingGalleryPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingGalleryPhotos();
            return result;
        }
    }
    async getPendingRegistrations(): Promise<Array<PendingRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRegistrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRegistrations();
            return result;
        }
    }
    async getRelationshipRequests(): Promise<Array<RelationshipRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelationshipRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelationshipRequests();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByEmail(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByEmail(arg0);
                return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByEmail(arg0);
            return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserActive(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserActive(arg0);
            return result;
        }
    }
    async loginWithPassword(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithPassword(arg0, arg1);
                return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithPassword(arg0, arg1);
            return from_candid_UserProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserProfile_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserProfile_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async rejectRegistration(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRegistration(arg0);
            return result;
        }
    }
    async rejectRelationshipRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRelationshipRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRelationshipRequest(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitPendingRegistration(arg0: PendingRegistration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPendingRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPendingRegistration(arg0);
            return result;
        }
    }
    async submitRelationshipRequest(arg0: RelationshipRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRelationshipRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRelationshipRequest(arg0);
            return result;
        }
    }
    async updateFamilyMember(arg0: FamilyMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFamilyMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFamilyMember(arg0);
            return result;
        }
    }
    async updateGalleryPhotoCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryPhotoCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryPhotoCategory(arg0, arg1);
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    passwordHash: string;
}): {
    id: string;
    name: string;
    createdAt: Time;
    role: UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    passwordHash: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n6(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        isVerified: value.isVerified,
        passwordHash: value.passwordHash
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: Time;
    role: UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    passwordHash: string;
}): {
    id: string;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    isActive: boolean;
    email: string;
    isVerified: boolean;
    passwordHash: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n1(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        isVerified: value.isVerified,
        passwordHash: value.passwordHash
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
